# Generated by Django 4.2.2 on 2023-07-24 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('s_account', '0002_alter_account_wereda_name_alter_account_zone_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sectors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sector_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=100)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department')),
                ('sectors_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sectors')),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('birthday', models.DateTimeField()),
                ('gender', models.CharField(choices=[('malle', 'M'), ('FEMALE', 'F')], max_length=6)),
                ('data_of_employement', models.DateTimeField()),
                ('office_floor_no', models.CharField(max_length=50)),
                ('office_no', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.department')),
                ('position_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.position')),
                ('region_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='s_account.region')),
                ('sector_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.sectors')),
                ('stock_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='s_account.stock')),
                ('wereda_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='s_account.wereda')),
                ('zone_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='s_account.zone')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='sectors_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sectors'),
        ),
    ]
