# Generated by Django 4.2.2 on 2023-07-24 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='sectors_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.sectors'),
        ),
    ]
