# Generated by Django 4.2.2 on 2023-07-24 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_department_sectors_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='position',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='position',
            name='sectors_name',
        ),
    ]
