# Generated by Django 4.2.2 on 2023-07-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_department_department_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='sectors_name',
        ),
        migrations.AddField(
            model_name='department',
            name='department_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
