# Generated by Django 4.2.2 on 2023-07-19 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Wereda_name',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_account.wereda'),
        ),
        migrations.AlterField(
            model_name='account',
            name='Zone_name',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_account.zone'),
        ),
        migrations.AlterField(
            model_name='account',
            name='region_name',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_account.region'),
        ),
        migrations.AlterField(
            model_name='account',
            name='stock_name',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_account.stock'),
        ),
    ]
