# Generated by Django 4.2.2 on 2023-07-24 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('s_account', '0002_alter_account_wereda_name_alter_account_zone_name_and_more'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Catagory_name', models.CharField(max_length=50)),
                ('Catagory_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_code', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('Item_type', models.CharField(choices=[('fixed', 'Fixed'), ('periodical', 'periodical'), ('consumable', 'consumable')], max_length=50)),
                ('Current_Quantity', models.IntegerField()),
                ('scrap_value', models.IntegerField(default='', null=True)),
                ('cost', models.IntegerField(default='', null=True)),
                ('lift_span', models.IntegerField(default='', null=True)),
                ('Catagory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.catagories')),
                ('Wereda_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_account.wereda')),
                ('Zone_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_account.zone')),
                ('region_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_account.region')),
                ('stock_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_account.stock')),
            ],
        ),
        migrations.CreateModel(
            name='subcatagories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subcatagories_name', models.CharField(max_length=100)),
                ('subcatagories_code', models.CharField(max_length=50)),
                ('Catagory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.catagories')),
            ],
        ),
        migrations.CreateModel(
            name='retrun_item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('return_date', models.DateTimeField()),
                ('taken_Item_status', models.CharField(choices=[('New', 'New'), ('slightly_used', 'slightly_used'), ('damaged', 'damaged')], max_length=50)),
                ('return_case', models.CharField(choices=[('due_leave', 'due_leave'), ('due_damage', 'due_damage'), ('change', 'change')], max_length=50)),
                ('return_Description', models.TextField(max_length=500)),
                ('issued_by', models.CharField(max_length=100)),
                ('recipant_name', models.CharField(max_length=100)),
                ('Catagory_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.catagories')),
                ('Item_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.item')),
                ('Wereda_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_account.wereda')),
                ('Zone_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_account.zone')),
                ('region_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_account.region')),
                ('return_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.employee')),
                ('return_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='s_account.stock')),
                ('subcatagory_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.subcatagories')),
            ],
        ),
        migrations.CreateModel(
            name='oreder_item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ordered_date', models.DateTimeField()),
                ('order_Item_type', models.CharField(choices=[('argent', 'argent'), ('3_month', '3_month'), ('6_month', '6_month')], max_length=50)),
                ('ordered_case', models.CharField(choices=[('for direct use', 'for direct use'), ('to store', 'to store')], max_length=50)),
                ('order_Description', models.TextField(max_length=500)),
                ('ordered_by', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('Catagory_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.catagories')),
                ('Wereda_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_account.wereda')),
                ('Zone_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_account.zone')),
                ('ordered_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='s_account.stock')),
                ('ordered_item_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.item')),
                ('region_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_account.region')),
                ('subcatagory_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.subcatagories')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='sub_Catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.subcatagories'),
        ),
        migrations.CreateModel(
            name='Issused_item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('issuse_date', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('taken_Item_status', models.CharField(choices=[('New', 'New'), ('slightly_used', 'slightly_used'), ('damaged', 'damaged')], max_length=50)),
                ('Item_Description', models.TextField(max_length=500)),
                ('issued_by', models.CharField(max_length=100)),
                ('Catagory_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.catagories')),
                ('Item_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.item')),
                ('Wereda_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_account.wereda')),
                ('Zone_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_account.zone')),
                ('issue_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.employee')),
                ('region_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_account.region')),
                ('stock_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_account.stock')),
                ('subcatagory_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.subcatagories')),
            ],
        ),
        migrations.CreateModel(
            name='general_notify',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notify_date', models.DateTimeField()),
                ('notify_by', models.CharField(max_length=100)),
                ('notification_type', models.CharField(choices=[('question', 'question'), ('report', 'report'), ('other', 'other')], max_length=50)),
                ('notification', models.TextField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('Wereda_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_account.wereda')),
                ('Zone_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_account.zone')),
                ('notify_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='s_account.stock')),
                ('region_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='s_account.region')),
            ],
        ),
    ]
